server:
  port: 8080

spring:
  application:
    name: chat-app
  data:
    mongodb:
      uri: mongodb://localhost:27017/chatdb
      auto-index-creation: true
  jackson:
    time-zone: UTC

logging:
  level:
    com.harsh.chat: DEBUG
    org.springframework.web: DEBUG

cors:
  allowed-origin: http://localhost:5173

websocket:
  allowed-origin: http://localhost:5173
  heartbeat-interbal: 25000