server:
  port: 8080
  compression:
    enabled: true

spring:
  application:
    name: chat-app
  data:
    mongodb:
      uri: mongodb://localhost:27017/chatdb
      auto-index-creation: true
  jackson:
    time-zone: UTC
    default-property-inclusion: non_null


logging:
  level:
    com.harsh.chat: DEBUG
    org.springframework.web: DEBUG

jwt:
  secret: ${JWT_SECRET:mySuperSecretKeyForJWTGenerationThatShouldBeAtLeast32BytesLong}
  expiration: 86400000  # 24 hours
  refresh-expiration: 604800000  # 7 days

cors:
  allowed-origin: http://localhost:5173

websocket:
  allowed-origin: http://localhost:5173
  heartbeat-internal: 25000